services:
  caddy:
    image: caddy:alpine
    container_name: obsidian-caddy
    restart: unless-stopped
    ports:
      - "3880:3880"
      - "443:443"  # HTTPS port for Let's Encrypt
      - "80:80"    # HTTP port for Let's Encrypt challenges
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - couchdb
      - obsidian
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "caddy", "validate", "--config", "/etc/caddy/Caddyfile"]
      interval: 30s
      timeout: 10s
      retries: 3

  couchdb:
    image: couchdb:3.5.0
    container_name: obsidian-couchdb
    restart: unless-stopped
    ports:
      - "5984:5984"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      # Set proper user and group IDs for permission handling
      PUID: ${PUID}
      PGID: ${PGID}
      # Set timezone
      TZ: ${TZ}
      # CouchDB admin credentials (from .env file)
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    volumes:
      # Persistent data storage
      - couchdb_data:/opt/couchdb/data
      # Configuration storage
      - couchdb_config:/opt/couchdb/etc/local.d
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f -u $$COUCHDB_USER:$$COUCHDB_PASSWORD http://localhost:5984"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  obsidian-init:
    image: alpine:latest
    container_name: obsidian-init
    volumes:
      - obsidian_config:/config
    command: |
      sh -c '
        mkdir -p /config/.config/obsidian
        echo "{"                                                > /config/.config/obsidian/obsidian.json
        echo "  \"vaults\": {"                                 >> /config/.config/obsidian/obsidian.json
        echo "    \"knowledge_vault\": {"                      >> /config/.config/obsidian/obsidian.json
        echo "      \"path\": \"/obsidian/vault\","            >> /config/.config/obsidian/obsidian.json
        echo "      \"ts\": $(date +%s)000,"                   >> /config/.config/obsidian/obsidian.json
        echo "      \"open\": true"                            >> /config/.config/obsidian/obsidian.json
        echo "    }"                                           >> /config/.config/obsidian/obsidian.json
        echo "  }"                                             >> /config/.config/obsidian/obsidian.json
        echo "}"                                               >> /config/.config/obsidian/obsidian.json
        echo "Obsidian vault configuration complete - pointing to /obsidian/vault"
      '

  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian-app
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    shm_size: "1gb"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/New_York}
    volumes:
      - obsidian_config:/config
      - ./knowledge:/obsidian/vault:rw
    ports:
      - "3850:3000"  # LinuxServer container uses port 3000
      - "27124:27124"  # REST API HTTPS access
      - "27123:27123"  # REST API HTTP access
      - "3001:3001"  # Native MCP plugin access
    depends_on:
      - couchdb
      - obsidian-init
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  mcp-obsidian:
    build:
      context: .
      dockerfile: Dockerfile.mcp-obsidian
    container_name: obsidian-mcp-server
    restart: unless-stopped
    network_mode: host
    environment:
      - OBSIDIAN_HOST=127.0.0.1
      - OBSIDIAN_PORT=27124
      - OBSIDIAN_API_KEY=${OBSIDIAN_API_KEY}
      - OBSIDIAN_VERIFY_SSL=false
    depends_on:
      - obsidian
      - caddy
    # MCP server runs over stdio - no ports needed for external access
    # It will be used by external Claude Code clients via stdio interface

volumes:
  couchdb_data:
    driver: local
  couchdb_config:
    driver: local
  obsidian_config:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local