services:
  couchdb:
    image: couchdb:3.5.0
    container_name: obsidian-couchdb
    restart: unless-stopped
    ports:
      - "5984:5984"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      # Set proper user and group IDs for permission handling
      PUID: ${PUID}
      PGID: ${PGID}
      # Set timezone
      TZ: ${TZ}
      # CouchDB admin credentials (from .env file)
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    volumes:
      # Persistent data storage
      - couchdb_data:/opt/couchdb/data
      # Configuration storage
      - couchdb_config:/opt/couchdb/etc/local.d
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f -u $$COUCHDB_USER:$$COUCHDB_PASSWORD http://localhost:5984"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  couchdb_data:
    driver: local
  couchdb_config:
    driver: local